/**
 * comfy-setup.js — ComfyUI 智能管理脚本生成器（跨平台）
 *
 * 首次运行（或 comfyui 命令不存在）时自动检测系统环境，生成平台适配的
 * 智能管理脚本（start/stop/status 三合一），供 batch-screenshot.js /
 * comfy-lifecycle.js 统一调用。
 *
 * 设计原则（最简版）：
 *   - comfyui 命令已存在 → 直接用，不覆盖、不检查
 *   - 不存在 → detect() 检测环境 → generate() 生成
 *   - 检测失败（找不到 ComfyUI/python）→ 提示配环境变量，不阻断调用方
 *
 * 用法：
 *   const setup = require('./comfy-setup.js');
 *   setup.ensureComfyScript();     // 命令存在则跳过，否则生成
 *
 * 手动生成报告：
 *   node comfy-setup.js
 *
 * 环境变量：
 *   COMFYUI_DIR       ComfyUI 安装目录（优先于自动检测）
 *   COMFYUI_PYTHON    python 解释器路径（优先于自动检测）
 */

'use strict';

const fs = require('fs');
const path = require('path');
const os = require('os');
const { execSync } = require('child_process');

// ─── 路径常量 ────────────────────────────────────────
function scriptDir() {
  return path.join(os.homedir(), '.local', 'bin');
}
function scriptPath() {
  return path.join(scriptDir(), process.platform === 'win32' ? 'comfyui.ps1' : 'comfyui');
}

// ─── 环境检测 ────────────────────────────────────────
function detect() {
  const platform = process.platform; // linux | darwin | win32
  const comfyDir = findComfyDir();
  if (!comfyDir) return null;
  const pythonPath = findPython(comfyDir);
  if (!pythonPath) return null;
  return {
    platform,
    comfyDir,
    pythonPath,
    hasNvidiaSmi: hasCommand('nvidia-smi'),
  };
}

function findComfyDir() {
  const candidates = [];
  if (process.env.COMFYUI_DIR) candidates.push(process.env.COMFYUI_DIR);
  const home = os.homedir();
  candidates.push(path.join(home, 'ComfyUI'));
  candidates.push(path.join(home, 'comfyui'));
  if (platformHas(process.platform, 'linux', 'darwin')) candidates.push('/opt/ComfyUI');
  for (const dir of candidates) {
    if (fs.existsSync(path.join(dir, 'main.py'))) return dir;
  }
  return null;
}

function findPython(comfyDir) {
  if (process.env.COMFYUI_PYTHON && fs.existsSync(process.env.COMFYUI_PYTHON)) {
    return process.env.COMFYUI_PYTHON;
  }
  const isWin = process.platform === 'win32';
  const names = isWin
    ? ['.venv\\Scripts\\python.exe', 'venv\\Scripts\\python.exe']
    : ['.venv/bin/python', 'venv/bin/python'];
  for (const rel of names) {
    const p = path.join(comfyDir, rel);
    if (fs.existsSync(p)) return p;
  }
  // 兜底：系统 python
  const sysPy = isWin ? 'python' : 'python3';
  try {
    execSync(`${sysPy} --version`, { stdio: 'ignore' });
    return sysPy;
  } catch {}
  return null;
}

function hasCommand(cmd) {
  try {
    execSync(`${process.platform === 'win32' ? 'where' : 'which'} ${cmd}`, { stdio: 'ignore' });
    return true;
  } catch { return false; }
}

function platformHas(actual, ...wanted) { return wanted.includes(actual); }

// ─── 脚本生成 ────────────────────────────────────────
const SCRIPT_VERSION = 1;
const HEADER = `# comfyui smart script v${SCRIPT_VERSION} generated by snapflow comfy-setup`;

function generate(env, targetPath = scriptPath()) {
  const content = env.platform === 'win32' ? buildPs1(env) : buildBash(env);
  fs.mkdirSync(path.dirname(targetPath), { recursive: true });
  fs.writeFileSync(targetPath, content, 'utf-8');
  if (env.platform !== 'win32') fs.chmodSync(targetPath, 0o755);
  return targetPath;
}

function buildBash(env) {
  const gpuLine = env.hasNvidiaSmi
    ? `  nvidia-smi --query-gpu=name,memory.free --format=csv,noheader 2>/dev/null | head -1 && echo "   VRAM: $(nvidia-smi --query-gpu=memory.free --format=csv,noheader 2>/dev/null | head -1)"`
    : '  echo "   GPU: 未检测到 nvidia-smi"';
  return `#!/bin/bash
${HEADER}
# 用法: comfyui [start|stop|status]
# 由 comfy-setup.js 根据本机环境自动生成，请勿手动编辑（重跑会自动重新生成）

COMFY_DIR="${env.comfyDir}"
PYTHON="${env.pythonPath}"
PORT=8188
URL="http://127.0.0.1:$PORT"
LOG="$COMFY_DIR/comfyui.log"
PIDFILE="$COMFY_DIR/comfyui.pid"

is_running() {
  curl -s --max-time 3 "$URL/system_stats" >/dev/null 2>&1
}

start() {
  if is_running; then
    echo "✅ ComfyUI 已在运行: $URL"
    return 0
  fi
  if [ ! -f "$COMFY_DIR/main.py" ]; then
    echo "❌ ComfyUI 目录无效: $COMFY_DIR"
    return 1
  fi
  if [ ! -x "$PYTHON" ]; then
    echo "❌ python 不可执行: $PYTHON"
    return 1
  fi
  echo "🚀 启动 ComfyUI..."
  cd "$COMFY_DIR" || return 1
  nohup "$PYTHON" main.py --listen 127.0.0.1 --port $PORT >> "$LOG" 2>&1 &
  echo $! > "$PIDFILE"
  for i in $(seq 1 20); do
    sleep 3
    if is_running; then
      echo "✅ ComfyUI 已就绪: $URL  (耗时 ~$((i*3))s)"
      return 0
    fi
  done
  echo "❌ 启动超时,查看日志: $LOG"
  return 1
}

stop() {
  if ! is_running; then
    echo "ℹ️  ComfyUI 未在运行"
    return 0
  fi
  echo "🛑 停止 ComfyUI..."
  pkill -f "main.py --listen" 2>/dev/null
  sleep 3
  if is_running; then
    pkill -9 -f "main.py --listen" 2>/dev/null
    sleep 2
  fi
  is_running && echo "❌ 停止失败" || echo "✅ ComfyUI 已停止"
}

status() {
  if is_running; then
    echo "✅ ComfyUI 正在运行: $URL"
${gpuLine}
  else
    echo "❌ ComfyUI 未运行 (用 'comfyui start' 启动)"
  fi
}

case "\${1:-start}" in
  start)   start ;;
  stop)    stop ;;
  status)  status ;;
  *)       echo "用法: comfyui [start|stop|status]"; exit 1 ;;
esac
`;
}

function buildPs1(env) {
  const gpuLine = env.hasNvidiaSmi
    ? '  $gpu = & nvidia-smi --query-gpu=name,memory.free --format=csv,noheader 2>$null | Select-Object -First 1; Write-Host "   GPU: $gpu"'
    : '  Write-Host "   GPU: no nvidia-smi detected"';
  return `# ${HEADER}
# Usage: .\\comfyui.ps1 [start|stop|status]
# Generated by comfy-setup.js from this machine environment.

$ComfyDir = '${env.comfyDir}'
$Python = '${env.pythonPath}'
$Port = 8188
$Url = 'http://127.0.0.1:' + $Port
$Log = Join-Path $ComfyDir 'comfyui.log'

function Is-Running {
  try {
    $r = Invoke-WebRequest -Uri ($Url + '/system_stats') -TimeoutSec 3 -UseBasicParsing
    return $r.StatusCode -eq 200
  } catch { return $false }
}

function Start-ComfyUI {
  if (Is-Running) { Write-Host 'ComfyUI already running: ' $Url; return 0 }
  if (-not (Test-Path (Join-Path $ComfyDir 'main.py'))) { Write-Host 'Invalid ComfyUI dir: ' $ComfyDir; return 1 }
  if (-not (Test-Path $Python)) { Write-Host 'Python not found: ' $Python; return 1 }
  Write-Host 'Starting ComfyUI...'
  Start-Process -FilePath $Python -ArgumentList 'main.py','--listen','127.0.0.1','--port',$Port -WorkingDirectory $ComfyDir -RedirectStandardOutput $Log -RedirectStandardError ($Log + '.err') -WindowStyle Hidden
  for ($i = 0; $i -lt 20; $i++) {
    Start-Sleep -Seconds 3
    if (Is-Running) { Write-Host 'ComfyUI ready: ' $Url; return 0 }
  }
  Write-Host 'Start timeout, see log: ' $Log
  return 1
}

function Stop-ComfyUI {
  if (-not (Is-Running)) { Write-Host 'ComfyUI not running'; return 0 }
  Write-Host 'Stopping ComfyUI...'
  Get-Process python* -ErrorAction SilentlyContinue | Stop-Process -Force
  Start-Sleep -Seconds 3
  if (Is-Running) { Write-Host 'Stop failed' } else { Write-Host 'ComfyUI stopped' }
}

function Get-Status {
  if (Is-Running) {
    Write-Host 'ComfyUI running: ' $Url
${gpuLine}
  } else {
    Write-Host 'ComfyUI not running (use: comfyui.ps1 start)'
  }
}

switch ($args[0]) {
  'start'  { Start-ComfyUI }
  'stop'   { Stop-ComfyUI }
  'status' { Get-Status }
  default  { Write-Host 'Usage: .\\comfyui.ps1 [start|stop|status]'; exit 1 }
}
`;
}

// ─── 对外入口 ────────────────────────────────────────
/**
 * 确保 comfyui 智能脚本存在：
 *   - 已存在 → true（不覆盖、不检查）
 *   - 不存在 → 检测环境 → 生成 → true；检测失败 → false（不阻断调用方）
 */
function ensureComfyScript() {
  const target = scriptPath();
  if (fs.existsSync(target)) return true;
  const env = detect();
  if (!env) {
    console.warn('  ⚠ 未检测到 ComfyUI 环境（可用 COMFYUI_DIR / COMFYUI_PYTHON 指定），跳过脚本生成');
    return false;
  }
  try {
    generate(env, target);
    console.log(`  ✓ 已生成 ComfyUI 智能脚本: ${target}`);
    return true;
  } catch (err) {
    console.warn(`  ⚠ 脚本生成失败: ${err.message}`);
    return false;
  }
}

module.exports = { ensureComfyScript, detect, generate, scriptPath };

// ─── CLI 手动模式：检测 + 生成 + 报告 ─────────────────
if (require.main === module) {
  const target = scriptPath();
  const exists = fs.existsSync(target);
  console.log(`平台: ${process.platform}`);
  console.log(`目标脚本: ${target} ${exists ? '(已存在)' : '(不存在)'}`);
  if (exists) {
    console.log('→ comfyui 命令已存在，直接使用，跳过生成');
    process.exit(0);
  }
  const env = detect();
  if (!env) {
    console.log('→ 未检测到 ComfyUI 环境');
    console.log('  请设置环境变量后重试: COMFYUI_DIR=/path/to/ComfyUI [COMFYUI_PYTHON=/path/to/python]');
    process.exit(1);
  }
  console.log(`检测到 ComfyUI: ${env.comfyDir}`);
  console.log(`检测到 Python:  ${env.pythonPath}`);
  console.log(`GPU:            ${env.hasNvidiaSmi ? 'nvidia-smi 可用' : '未检测到 nvidia-smi'}`);
  generate(env, target);
  console.log(`→ 已生成: ${target}`);
}
